/**
 * SpurTalk Backend Semantic Audit Script
 * This script verifies that API responses match the expected semantic models.
 */

const axios = require('axios');

const API_URL = 'http://localhost:7101/api';
let AUTH_TOKEN = '';
let TEST_TASK_ID = '';

async function runAudit() {
    console.log('🚀 Starting Backend Semantic Audit...\n');

    try {
        // 1. Health Check
        console.log('--- [Health Check] ---');
        const health = await axios.get('http://localhost:7101/health');
        console.log('Status:', health.data.status, '\n');

        // 2. Auth: Register/Login
        console.log('--- [Auth & User Semantics] ---');
        const email = `test_audit_${Date.now()}@example.com`;
        await axios.post(`${API_URL}/auth/register`, { email, password: 'password123' });
        const login = await axios.post(`${API_URL}/auth/login`, { email, password: 'password123' });
        AUTH_TOKEN = login.data.tokens.accessToken;
        console.log('✅ Registered and Logged in.');
        console.log('User Prefs received (Semantics):', !!login.data.user.preferences, '\n');

        const headers = { Authorization: `Bearer ${AUTH_TOKEN}` };

        // 3. Task Semantics
        console.log('--- [Task Semantics] ---');
        const taskResponse = await axios.post(`${API_URL}/tasks`, {
            title: "Audit documentation",
            effortLevel: "Medium",
            fuzzyDeadline: "Soon",
            hardDeadline: new Date(Date.now() + 86400000 * 2).toISOString(),
            motivationCategory: "Achievement"
        }, { headers });
        TEST_TASK_ID = taskResponse.data.id;
        console.log('✅ Task Created with Effort:', taskResponse.data.effortLevel);
        console.log('✅ Motivation Category:', taskResponse.data.motivationCategory);
        console.log('✅ AI Compelling Event generated:', !!taskResponse.data.compellingEvent, `("${taskResponse.data.compellingEvent}")\n`);

        // 4. Focus Deck Semantics
        console.log('--- [Focus Deck] ---');
        const deck = await axios.get(`${API_URL}/tasks/deck`, { headers });
        console.log('Deck size:', deck.data.length);
        console.log('Top card title:', deck.data[0]?.title);

        // Swipe Down (Decompose)
        console.log('Swiping DOWN on task to trigger unblocker...');
        const swipe = await axios.post(`${API_URL}/tasks/deck/${TEST_TASK_ID}/swipe`, { direction: 'down' }, { headers });
        console.log('✅ Nano-steps generated:', swipe.data.nanoSteps?.length, '\n');
        console.log('✅ Nano-steps generated:', swipe.data.nanoSteps?.length);
        console.log('✅ Nano-steps generated by AI:', swipe.data.nanoSteps?.every(step => step.generatedByAI), '\n');

        // Swipe Right (Ready to start) -> Moves to Active
        console.log('Swiping RIGHT on task to move to Active...');
        await axios.post(`${API_URL}/tasks/deck/${TEST_TASK_ID}/swipe`, { direction: 'right' }, { headers });

        // 5. Timeline Stress Cluster & Buffer Day Semantics
        console.log('--- [Empathic Planner: Stress & Buffers] ---');
        // Create 3 more BIG tasks and move them to Active to trigger stress
        const tomorrow = new Date(Date.now() + 86400000).toISOString();
        for (let i = 0; i < 3; i++) {
            const t = await axios.post(`${API_URL}/tasks`, {
                title: `Big Task ${i} is very difficult`,
                description: "Detailed description for better AI decomposition",
                effortLevel: "Big",
                fuzzyDeadline: "Soon",
                hardDeadline: tomorrow
            }, { headers });
            // Move to active
            await axios.put(`${API_URL}/tasks/${t.data.id}`, { state: 'Active' }, { headers });
        }

        const empathicTimeline = await axios.get(`${API_URL}/timeline`, { headers });
        console.log('✅ Stress Clusters detected:', empathicTimeline.data.stressClusters?.length);
        console.log('✅ Buffer Days inserted:', empathicTimeline.data.bufferDays?.length);
        if (empathicTimeline.data.bufferDays?.length > 0) {
            console.log('✅ Buffer Day Reason:', empathicTimeline.data.bufferDays[0].reason);
        }

        // 6. Data Export (Compliance)
        console.log('--- [Compliance: Data Export] ---');
        const exportData = await axios.get(`${API_URL}/auth/export-data`, { headers });
        console.log('✅ Export data received. Task count:', exportData.data.tasks?.length);
        console.log('✅ Export includes preferences:', !!exportData.data.preferences);

        // 7. Garden Growth Semantics
        console.log('--- [Garden Semantics] ---');
        const garden = await axios.post(`${API_URL}/garden/complete/${TEST_TASK_ID}`, {}, { headers });
        const lastElement = garden.data.elements[garden.data.elements.length - 1];
        console.log('✅ Task completion grew a:', lastElement?.type); // Tree or flower
        console.log('✅ Psychological Safety Color assigned:', lastElement?.color);
        console.log('✅ Current Streak:', garden.data.currentStreak);
        console.log('✅ Sun Brightness:', garden.data.sunBrightness, '\n');

        console.log('✨ Audit Complete. All core semantic markers verified.');

    } catch (error) {
        console.error('❌ Audit Failed:');
        if (error.response) {
            console.error('Data:', error.response.data);
            console.error('Status:', error.response.status);
        } else {
            console.error(error.message);
        }
    }
}

runAudit();
